name = "digital-logbook"
main = "src/index.js"
compatibility_date = "2023-06-20"
usage_model = "bundled"
node_compat = true
env = { }
kv_namespaces = [
  { binding = "counterStore", id = "#TODO: Include ID here" }
]

[triggers]
crons = [ ]

[vars]

chatId1 = "#TODO: Include chatID1 here, this is the unfiltered chat"
chatId2 = "#TODO: Include chatID2 here, this is the filtered chat"
POST_URI = "#TODO: Include your POST_URI here, this is where your server is hosted"
HAS_ATTACHMENTS = false
openaccessset = [#TODO: Include the question numbers you want to include in the filtered chat here]
questionset = [#TODO: Include the question names that you want to replace the form questions with]

# The necessary secrets are:
# - botToken
# - formSecretKey
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
